name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: test_kbc_game
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      
      - name: Install system dependencies
        run: sudo apt-get install -y python3-dev libmysqlclient-dev
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h "127.0.0.1" --silent; then
              break
            fi
            echo "Waiting for MySQL... Attempt $i/10"
            sleep 2
          done
      
      - name: Setup database
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: python setup_db.py

      - name: Run tests
        run: pytest test_app.py

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt
      - run: flake8 .
