name: Flask CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Aditya@9476
          MYSQL_DATABASE: test_kbc_game
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libmysqlclient-dev mysql-client

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: |
        for i in {1..10}; do
          if mysqladmin ping -h 127.0.0.1 --silent; then
            break
          fi
          echo "Waiting for MySQL... Attempt $i/10"
          sleep 2
        done

    - name: Initialize database
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
      run: python setup_db.py

    - name: Run tests
      run: python -m unittest test_app.py
